#!/bin/bash

echo "Testing chonker7 notes functionality"
echo "====================================="
echo ""
echo "You can now run chonker7 in three ways:"
echo ""
echo "1. Run without arguments to open file picker:"
echo "   DYLD_LIBRARY_PATH=./lib ./target/release/chonker7"
echo ""
echo "2. Run with a PDF file:"
echo "   DYLD_LIBRARY_PATH=./lib ./target/release/chonker7 your_file.pdf"
echo ""
echo "3. Run directly in notes mode:"
echo "   DYLD_LIBRARY_PATH=./lib ./target/release/chonker7 notes"
echo ""
echo "Once running, use Ctrl+Shift+N to toggle between PDF and Notes modes"
echo ""
echo "Notes Mode Commands:"
echo "  Ctrl+N: Create new note"
echo "  Ctrl+S: Save current note"
echo "  Ctrl+L: List all notes"
echo "  Ctrl+F: Search notes"
echo "  Ctrl+Shift+N: Return to PDF mode"
echo ""
echo "PDF Mode Commands:"
echo "  Ctrl+Shift+N: Switch to Notes mode"
echo "  Ctrl+N: Next page"
echo "  Ctrl+P: Previous page"
echo "  Ctrl+T: Toggle extraction method"
echo "  Ctrl+O: Open file picker"
echo "  Ctrl+Q: Quit"